In [ ]:
# Scaling data with outliers
# use RobustScaler
from sklearn import preprocessing
import numpy as np
X_train= np.array([[1, 2, 3],
                   [4, 5, 6],
                   [3 ,6 ,8],
                   [7, 999, 999]])
X_train

array([[  1,   2,   3],
       [  4,   5,   6],
       [  3,   6,   8],
       [  7, 999, 999]])

In [ ]:
scaler = preprocessing.RobustScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled.round(2)

array([[-1.11, -0.01, -0.02],
       [ 0.22, -0.  , -0.  ],
       [-0.22,  0.  ,  0.  ],
       [ 1.56,  3.97,  3.96]])

In [ ]:
scaler = preprocessing.MinMaxScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled.round(2)

array([[0.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.  ],
       [0.33, 0.  , 0.01],
       [1.  , 1.  , 1.  ]])

In [ ]:
x= np.array([np.random.randint(0,10,50),
              np.random.randint(0,10,50)]).T
x = np.append(x, np.array([[5, 878999]]), axis =0)
x

array([[     2,      4],
       [     4,      4],
       [     0,      4],
       [     4,      6],
       [     7,      0],
       [     3,      5],
       [     2,      6],
       [     7,      4],
       [     1,      1],
       [     7,      0],
       [     0,      1],
       [     3,      2],
       [     5,      3],
       [     9,      4],
       [     7,      7],
       [     2,      6],
       [     5,      8],
       [     3,      8],
       [     7,      9],
       [     5,      7],
       [     3,      0],
       [     3,      0],
       [     7,      1],
       [     3,      9],
       [     9,      4],
       [     7,      6],
       [     9,      3],
       [     1,      5],
       [     3,      9],
       [     6,      3],
       [     6,      9],
       [     8,      8],
       [     9,      7],
       [     7,      4],
       [     1,      5],
       [     6,      9],
       [     8,      6],
       [     2,      7],
       [     5,      2],
       [     2,      2],


In [ ]:
scaler = preprocessing.MinMaxScaler().fit_transform(x)
scaler.round(2)

array([[0.89, 0.  ],
       [0.67, 0.  ],
       [0.22, 0.  ],
       [0.78, 0.  ],
       [0.  , 0.  ],
       [0.78, 0.  ],
       [0.89, 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 0.  ],
       [0.78, 0.  ],
       [1.  , 0.  ],
       [0.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.33, 0.  ],
       [0.89, 0.  ],
       [0.22, 0.  ],
       [0.67, 0.  ],
       [0.44, 0.  ],
       [0.22, 0.  ],
       [0.56, 0.  ],
       [0.78, 0.  ],
       [0.89, 0.  ],
       [0.11, 0.  ],
       [0.11, 0.  ],
       [0.11, 0.  ],
       [0.11, 0.  ],
       [0.67, 0.  ],
       [0.89, 0.  ],
       [0.44, 0.  ],
       [0.67, 0.  ],
       [0.89, 0.  ],
       [0.44, 0.  ],
       [0.89, 0.  ],
       [0.67, 0.  ],
       [0.56, 0.  ],
       [0.33, 0.  ],
       [0.78, 0.  ],
       [0.44, 0.  ],
       [0.44, 0.  ],
       [0.33, 0.  ],
       [0.22, 0.  ],
       [0.11, 0.  ],
       [0.22, 0.  ],
       [0.56, 0.  ],
       [0.78,

In [ ]:
scale=preprocessing.RobustScaler().fit_transform(x)
scale.round(3)

array([[ 6.000000e-01,  8.000000e-01],
       [ 2.000000e-01, -4.000000e-01],
       [-6.000000e-01,  8.000000e-01],
       [ 4.000000e-01, -8.000000e-01],
       [-1.000000e+00,  6.000000e-01],
       [ 4.000000e-01,  2.000000e-01],
       [ 6.000000e-01, -2.000000e-01],
       [ 8.000000e-01, -8.000000e-01],
       [ 8.000000e-01,  2.000000e-01],
       [ 8.000000e-01,  0.000000e+00],
       [-1.000000e+00,  6.000000e-01],
       [ 4.000000e-01,  4.000000e-01],
       [ 8.000000e-01,  0.000000e+00],
       [-1.000000e+00,  0.000000e+00],
       [ 8.000000e-01,  6.000000e-01],
       [ 8.000000e-01,  4.000000e-01],
       [-4.000000e-01,  2.000000e-01],
       [ 6.000000e-01, -6.000000e-01],
       [-6.000000e-01,  6.000000e-01],
       [ 2.000000e-01,  4.000000e-01],
       [-2.000000e-01,  6.000000e-01],
       [-6.000000e-01, -8.000000e-01],
       [ 0.000000e+00, -1.000000e+00],
       [ 4.000000e-01, -8.000000e-01],
       [ 6.000000e-01, -2.000000e-01],
       [-8.000000e-01,  6

**Outlier distort most scaling techniques**

  Value
- 10
- 12
- 13
- 15
- 10,000 (outlier 🚨)

StandardScaler subtracts the mean and divides by the standard deviation — both of which are heavily influenced by the huge value 10,000.

MinMaxScaler rescales values to [0, 1] using min and max, so 10,000 as the max makes all other values squished near 0.

As a result, “normal” data points lose their variation — they become indistinguishable from each other.

RobustScaler uses median and IQR (Interquartile Range) instead of mean and standard deviation.

    X' = X - Median(X)/IQR(X)
    IQR = Q3 - Q1
    where Q3= 75th percentile, Q1=25th percentile

- The median and IQR are robust statistics — they don’t change much even when extreme outliers are present.

- So main data distribution (the “central mass” of points) is preserved and well-scaled.

- The outliers remain far away (which is good — the model can still detect them).



